// export const taluk = ["Thiruvanathapuram", "Nedumangad",'Chirayinkeezhu'];

export const locationsData = [
  {
    id: 1,
    taluk: "Thiruvanathapuram",
    locations: [
      "Thycadu",
      "Sasthamangalam",
      "Vattiyurkavu",
      "Kowdiar",
      "Peroorkada",
      "Kudappanakunnu",
      "Pattom",
      "Ulloor",
      "Cheruvaikal",
      "Attipra",
      "Kadakampalli",
      "Pettah",
      "Vanchiyur",
      "Muttathara",
      "Manacaud",
      "Thiruvallam",
      "Nemom",
      "Thirumala",
    ],
  },
  {
    id: 2,
    taluk: "Nedumangad",
    locations: [
      "Anad",
      "Aruvikkara",
      "Aryanad",
      "Kallara",
      "Karakulam",
      "Karippooru",
      "Koliyakode",
      "Kurupuzha",
      "Manikkal",
      "Nedumangad",
      "Nellanad",
      "Palode",
      "Panavoor",
      "Pangode",
      "Peringamala",
      "Pullampara",
      "Theakada",
      "Thennoor",
      "Tholicode",
      "Uzhamalackal",
      "Vamanapuram",
      "Vattappara",
      "Vellanad",
      "Vembayam",
      "Vithura",
    ],
  },
  {
    id: 3,
    taluk: "Chirayinkeezhu",
    locations: [
      "Alamcode",
      "Azhoor",
      "Chirayinkeezhu",
      "Edakkode",
      "Kadakkavoor",
      "Keezhattingal",
      "Kilimanoor",
      "Ponganadu",
      "Koonthalloor",
      "Koduvazhannoor",
      "Mudakkal",
      "Nagaroor",
      "Pazhayakunnummel",
      "Perunguzhi",
      "Pulimath",
      "Sarkara-Chirayinkeezhu",
      "Vakkom",
      "Vellalloor",
    ],
  },
  {
    id: 4,
    taluk: "Kattakada",
    locations: [
      "Amboori",
      "Kallikkad",
      "Keezharoor",
      "Kulathummal",
      "Malayinkeezhu",
      "Mannoorkara",
      "Maranalloor",
      "Ottasekharamangalam",
      "Perumkulam",
      "Vazhichal",
    ],
  },
  {
    id: 5,
    taluk: "Neyyattinkara",
    locations: [
      "Anavoor",
      "Athiyannur",
      "Balaramapuram",
      "Chenkal",
      "Kanjiramkulam",
      "Karode",
      "Karumkulam",
      "Kollayil",
      "Kottukal",
      "Kulathoor",
      "Kunnathukal",
      "Neyyattinkara",
      "Pallichal",
      "Parassala",
      "Parasuvaikkal",
      "Perumkadavila",
      "Perumpazhuthoor",
      "Poovar",
      "Thirupuram",
      "Vellarada",
      "Vizhinjam",
    ],
  },
  {
    id: 6,
    taluk: "Varkala",
    locations: [
      "Ayiroor",
      "Chemmaruthy",
      "Cherunniyoor",
      "Edava",
      "Manamboor",
      "Ottoor",
      "Vettoor",
    ],
  },
];
